### 1
GET http://localhost:3000/players/

### 2


POST http://localhost:3000/players/
Content-Type: application/json

{
  "player_name": "Vishal",
  "jersey_number": 17,
  "role": "Bowler"
}
### 3

GET http://localhost:3000/players/5/ 

### 4

PUT http://localhost:3000/players/7/
Content-Type: application/json

{
  "player_name": "Maneesh",
  "jersey_number": 54,
  "role": "All-rounder"
}
### 5
DELETE http://localhost:3000/players/7/